name: 'Terraform Azure Resource Group'

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 'latest'

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Initialize Terraform
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    - name: Terraform Plan
      run: terraform plan
      #env:
      #  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      #  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      #  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      #env:
      #  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      #  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      #  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
